version: '3.3'
services:
  mongodb_business:
    container_name: mongo_db
    image: mongo
    expose:
      - "27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./compose_mongodb/database:/data/db

  backend_business:
    build: .
    container_name: business
    image: backend_business
    ports:
      - "8002:8002"
    expose:
      - "8002"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb_business
      
  backend_payments:
    build: ../taller2-ubademy-payments
    container_name: payments
    image: backend_payments
    ports:
      - "8003:8003"
    expose:
      - "8003"
    volumes:
      - ../taller2-ubademy-payments:/app 
      - /app/node_modules
    depends_on:
      - mongodb_business
