version: '3.3'
services: 
  mongo_db:
    image: mongo:latest
    container_name: mongo-container
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - my-network

  backend_business:
    build: .
    container_name: compose_backend_business
    image: backend_business
    environment:
      - DATABASE_URL="mongodb://mongoadmin:secret@mongo_db:27017/"
    ports:
      - "8001:8001"
    expose:
      - "8001"
    volumes:
      - ./../taller2-ubademy-users:/app
    depends_on:
      - mongo_db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
