version: '3.3'
services:
  mongodb_business:
    container_name: mongo_db
    image: mongo
    expose:
      - "27017"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./compose_mongodb/database:/data/db

  backend_business:
    build: .
    container_name: business
    image: backend_business
    ports:
      - "8002:8002"
    expose:
      - "8002"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb_business
