name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npx nyc npm test
    
    - name: Generate coverage
      run: npx nyc report --reporter=json
    
    - name: Upload coverage to Codecov
      run: npx codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage/coverage-final.json
